Add export type documentation (+ small updates)
projecttacoma/bulk-submit-data-docs pull request #5
Opened 2022-11-07 21:39 UTC by sarahmcdougall

# Summary
Adds documentation for the `exportType` parameter, adds it to an example, and adds other small changes to the OperationDefinition.

# Testing Guidance
- To run locally, navigate to the `BulkSubmitData` directory and run `./_genonce.sh`. You may need to run the `./_updatePublisher.sh` script first if the publisher cannot be found.
- Open `output/index.html` to see the IG.
- Check that all parameters are accounted for, all examples are accurate, etc. Check the [bulk import pnp proposal](https://github.com/smart-on-fhir/bulk-import/blob/master/import-pnp.md#parameters) to see if anything included in that proposal should also be reflected in this operation definition

**Question:** Is it worth adding anything to the OperationDefinition about how the supplied parameters may include additional FHIR Bulk Data Export kickoff parameters (e.g. `_since`)?

2022-11-08 22:29 UTC, mgramigna requested changes
Changes to the spec itself look great. One thing we should probably do as we prepare to submit this to DEQM is update the canonical in sushi-config.yml, which will allow the operation definition to be properly specified:

Change `canonical` to `http://hl7.org/fhir/us/davinci-deqm` in `sushi-config`

2022-11-09 16:57 UTC, p9g commented
I'm a little concerned that http://hl7.org/fhir/R4/async.html **requires** the prefer HTTP header, so doing the current (synchronous) $submit-data would now need prefer: ??? (not respond-async).  The current $submit-data does not require the prefer header as far as I know.

I don't think the OperationDefinition has a computable way of saying to use the Async pattern; it is just stated in the text or description.

The markdown (.md) talks about the required header, but it should probably be stated in the FSH somewhere also.

2022-11-09 17:09 UTC, mgramigna commented
> I'm a little concerned that http://hl7.org/fhir/R4/async.html **requires** the prefer HTTP header, so doing the current (synchronous) $submit-data would now need prefer: ??? (not respond-async). The current $submit-data does not require the prefer header as far as I know.
> 
> I don't think the OperationDefinition has a computable way of saying to use the Async pattern; it is just stated in the text or description.
> 
> The markdown (.md) talks about the required header, but it should probably be stated in the FSH somewhere also.

I believe omission of the `prefer` header would trigger the synchronous submit data, it doesn't need to be set to a different value. I don't know of a way to specify a required header within the OperationDefinition itself (only required parameters)

2022-11-09 20:53 UTC, mgramigna approved these changes
I'm gonna push this through. We will make/resolve any other changes via the JSON of the operation def

2022-11-09 20:54 UTC, merged